FROM jenkins/jenkins:2.414.3-jdk17
#image from the jenkins website

USER root
RUN apt-get update && apt-get install -y lsb-release

#Adding the Jenkins automate installation Key to system
RUN curl -fsSLo /usr/share/keyrings/docker-archive-keyring.asc \
  https://download.docker.com/linux/debian/gpg

#Add Jenkins APT Repository Entry
RUN echo "deb [arch=$(dpkg --print-architecture) \
  signed-by=/usr/share/keyrings/docker-archive-keyring.asc] \
  https://download.docker.com/linux/debian \
  $(lsb_release -cs) stable" > /etc/apt/sources.list.d/docker.list

#Installing the needed dependensies
USER root
#RUN apt-get install -y docker-ce-cli
RUN apt-get install -y sudo make gcc file

#Installing the plugins :
USER jenkins
RUN jenkins-plugin-cli --plugins "clone-workspace-scm"
RUN jenkins-plugin-cli --plugins "groovy"
RUN jenkins-plugin-cli --plugins docker-plugin:1.5
